dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
packages:
  github.com/mythvcode/storm-control/internal/watcher:
    config:
      all: True
  github.com/mythvcode/storm-control/internal/exporter:
    config:
      all: True
