# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:           # Запуск на каждый коммит
    branches:     # В любых ветках
      - '**'
  pull_request:
    branches:     # На каждом pull request
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ vars.GO_VERSION }}
    - name: Test
      run: make tests
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ vars.GO_VERSION }}
    - name: Lint
      run: make lint
